name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'family-growth-tracker/package-lock.json'

      - name: Install dependencies
        run: |
          cd family-growth-tracker
          npm ci

      - name: Generate Prisma client
        run: |
          cd family-growth-tracker
          npm run prisma:generate

      - name: Build application
        run: |
          cd family-growth-tracker
          npm run build

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@v1.4.0
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production